In [49]:
import numpy as np
import pandas as pd

In [50]:
df = pd.read_csv('customer.csv')
df.sample(5)

    age  gender review education purchased
7    60  Female   Poor    School       Yes
12   51    Male   Poor    School        No
11   74    Male   Good        UG       Yes
43   27    Male   Poor        PG        No
19   97    Male   Poor        PG       Yes

In [51]:
df = df.iloc[:,2:]

In [52]:
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [53]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(df.iloc[:,:2], df.iloc[:,-1],test_size=0.2 )

In [54]:
X_train

     review education
46     Poor        PG
23     Good    School
25     Good    School
7      Poor    School
12     Poor    School
21  Average        PG
44  Average        UG
49     Good        UG
35     Poor    School
42     Good        PG
34  Average    School
47     Good        PG
38     Good    School
39     Poor        PG
9      Good        UG
30  Average        UG
24  Average        PG
5   Average    School
18     Good    School
28     Poor    School
8   Average        UG
3      Good        PG
32  Average        UG
2      Good        PG
11     Good        UG
36     Good        UG
14     Poor        PG
13  Average    School
17     Poor        UG
37  Average        PG
4   Average        UG
31     Poor    School
27     Poor        PG
45     Poor        PG
41     Good        PG
0   Average    School
48     Good        UG
19     Poor        PG
26     Poor        PG
15     Poor        UG

#Ordinal Encoder

In [55]:
from sklearn.preprocessing import OrdinalEncoder
from sklearn.model_selection import train_test_split

# Re-split to ensure X_train contains the original string categories for encoding
X_train_str, _, _, _ = train_test_split(df.iloc[:,:2], df.iloc[:,-1],test_size=0.2 )

oe = OrdinalEncoder(categories=[['Poor', 'Average', 'Good'],['School','UG','PG']])
oe.fit(X_train_str)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [56]:
X_train = oe.transform(X_train)
X_train

array([[0., 2.],
       [2., 0.],
       [2., 0.],
       [0., 0.],
       [0., 0.],
       [1., 2.],
       [1., 1.],
       [2., 1.],
       [0., 0.],
       [2., 2.],
       [1., 0.],
       [2., 2.],
       [2., 0.],
       [0., 2.],
       [2., 1.],
       [1., 1.],
       [1., 2.],
       [1., 0.],
       [2., 0.],
       [0., 0.],
       [1., 1.],
       [2., 2.],
       [1., 1.],
       [2., 2.],
       [2., 1.],
       [2., 1.],
       [0., 2.],
       [1., 0.],
       [0., 1.],
       [1., 2.],
       [1., 1.],
       [0., 0.],
       [0., 2.],
       [0., 2.],
       [2., 2.],
       [1., 0.],
       [2., 1.],
       [0., 2.],
       [0., 2.],
       [0., 1.]])

In [58]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

# Label Encoder

In [59]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit(Y_train)

LabelEncoder()

In [60]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [63]:
y_train = le.transform(Y_train)
y_test = le.transform(Y_test)

In [64]:
y_train

array([0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0])